Add staging and production users for fenestra.
osuosl-cookbooks/osl-app pull request #24
Opened 2017-01-10 20:52 UTC by LyonesGamer

In preparation for moving Fenestra to an Ansible deployment, create both a staging and production user for fenestra, including data bags.

2017-01-10 22:50 UTC, fahlmant requested changes
`.rubocop.yml` needs to be brought up to date.

PR will need to be made against the `data_bags` repo to create those users in prod.

Please update the kitchen and chefspec tests to test what you added here.

2017-01-11 18:22 UTC, jldugger approved these changes
should probably update .rubocop.yml from [code_generator](https://github.com/osuosl-cookbooks/code_generator/blob/master/files/default/rubocop.yml), but fine otherwise.

2017-02-01 19:09 UTC, fahlmant commented
@LyonesGamer Are you still working on this?

2017-02-02 19:30 UTC, LyonesGamer commented
@fahlmant Yes, I've just been busy with other things, this has been low priority for me.

2017-04-14 21:29 UTC, fahlmant requested changes

2017-04-14 21:29 UTC, fahlmant commented on spec/app1_spec.rb
> +  %w(fenestra-staging-unicorn fenestra-production-unicorn).each do |s|
In the recipe you call these `fenestra-staging_service` and `fenestra-production_service`

2017-04-14 21:36 UTC, fahlmant commented on .rubocop.yml
> +    - 'files/default/build_cookbook/test-fixture-recipe.rb'
Why was this added? This file doesn't exist in this repo

2017-04-20 20:49 UTC, fahlmant commented on .rubocop.yml
> +    - 'files/default/build_cookbook/test-fixture-recipe.rb'
This can be removed

2017-04-20 20:52 UTC, fahlmant approved these changes

2017-04-20 22:53 UTC, ramereth approved these changes

2017-04-20 23:08 UTC, LyonesGamer commented
I'm going to wait for the other PRs I have for the data bags to be ready and reviewed before I merge this, because this will break the current fenestra user.

2017-04-20 23:09 UTC, fahlmant commented
@LyonesGamer dont foget to use the `bump` command instead of manually merging it. :)

2017-05-03 14:46 UTC, fahlmant commented
@LyonesGamer Still planning on merging this?

2018-07-25 21:41 UTC, closed without merging